
CREATE TABLE car (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    price NUMERIC(19, 2) NOT NULL
);
INSERT INTO car (make, model, price) values ('Ford', 'B-Class', '30840.13');
INSERT INTO car (make, model, price) values ('Isuzu', 'X1', '10000.06');
INSERT INTO car (make, model, price) values ('Ford', 'Impreza', '10003.55');
INSERT INTO car (make, model, price) values ('Toyota', 'Sebring', '11868.77');
INSERT INTO car (make, model, price) values ('Nissan', 'Escort', '10005.83');
INSERT INTO car (make, model, price) values ('Ford', 'Canyon Extended Cab', '10005.2');
INSERT INTO car (make, model, price) values ('Volkswagen', 'F250 Super Duty Regular Cab', '10056.36');
INSERT INTO car (make, model, price) values ('Lexus', 'Savana 3500 Cargo', '101834.44');
INSERT INTO car (make, model, price) values ('HUMMER', 'Mercedes-AMG S-Class', '26904.94');
INSERT INTO car (make, model, price) values ('Audi', 'Equinox', '83659.13');
INSERT INTO car (make, model, price) values ('Ford', 'A8', '10008.91');
INSERT INTO car (make, model, price) values ('Ford', 'Q', '10055.48');
INSERT INTO car (make, model, price) values ('Land Rover', 'Rogue', '10237.73');
INSERT INTO car (make, model, price) values ('Subaru', 'Avenger', '10048.95');
INSERT INTO car (make, model, price) values ('GMC', 'A5', '33714.77');
INSERT INTO car (make, model, price) values ('Lexus', 'S10 Regular Cab', '13351.7');
INSERT INTO car (make, model, price) values ('Jeep', 'A6', '10768.3');
INSERT INTO car (make, model, price) values ('Dodge', 'Quest', '13086.88');
INSERT INTO car (make, model, price) values ('Ford', '7 Series', '10007.5');
INSERT INTO car (make, model, price) values ('Nissan', 'Wrangler', '10000.44');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Accent', '11835.84');
INSERT INTO car (make, model, price) values ('Honda', 'Z4', '10611.83');
INSERT INTO car (make, model, price) values ('INFINITI', '1500 Regular Cab', '14949.81');
INSERT INTO car (make, model, price) values ('Land Rover', 'Vandura 1500', '10001.58');
INSERT INTO car (make, model, price) values ('Dodge', 'Concorde', '10039.2');
INSERT INTO car (make, model, price) values ('GMC', 'Bronco', '10006.26');
INSERT INTO car (make, model, price) values ('Kia', '86', '10004.69');
INSERT INTO car (make, model, price) values ('Pontiac', 'Freestar Cargo', '10004.49');
INSERT INTO car (make, model, price) values ('BMW', 'Grand Cherokee', '10004.14');
INSERT INTO car (make, model, price) values ('Toyota', 'Tundra Regular Cab', '10003.43');
INSERT INTO car (make, model, price) values ('Kia', 'Intrepid', '10003.93');
INSERT INTO car (make, model, price) values ('MINI', 'GT-R', '10728.39');
INSERT INTO car (make, model, price) values ('Cadillac', 'A8', '19582.11');
INSERT INTO car (make, model, price) values ('Jeep', 'Windstar Cargo', '10007.69');
INSERT INTO car (make, model, price) values ('MAZDA', 'Savana 1500 Passenger', '10547.64');
INSERT INTO car (make, model, price) values ('Lamborghini', 'Ram Van 1500', '15677.27');
INSERT INTO car (make, model, price) values ('Honda', 'Encore', '10005.16');
INSERT INTO car (make, model, price) values ('MAZDA', 'Suburban 2500', '10925.88');
INSERT INTO car (make, model, price) values ('Nissan', 'Solara', '14431.62');
INSERT INTO car (make, model, price) values ('Audi', 'Swift', '13546.22');
INSERT INTO car (make, model, price) values ('BMW', 'Celica', '10006.96');
INSERT INTO car (make, model, price) values ('MINI', 'Quattroporte', '10566.07');
INSERT INTO car (make, model, price) values ('Nissan', 'S2000', '17642.98');
INSERT INTO car (make, model, price) values ('Audi', 'BRZ', '60086.62');
INSERT INTO car (make, model, price) values ('Dodge', 'Galant', '10039.51');
INSERT INTO car (make, model, price) values ('Nissan', '300 TE', '22858.95');
INSERT INTO car (make, model, price) values ('Cadillac', 'VUE', '10050.39');
INSERT INTO car (make, model, price) values ('Saab', 'Taurus', '10097.33');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Maxima', '31217.93');
INSERT INTO car (make, model, price) values ('Subaru', 'Continental', '17462.31');
INSERT INTO car (make, model, price) values ('Hyundai', 'Armada', '10001.39');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Malibu', '89110.66');
INSERT INTO car (make, model, price) values ('Ford', '5-Sep', '10006.65');
INSERT INTO car (make, model, price) values ('Volvo', 'Legacy', '10004.25');
INSERT INTO car (make, model, price) values ('Chevrolet', 'GLA', '10004.89');
INSERT INTO car (make, model, price) values ('BMW', 'Ram Van 1500', '30965.93');
INSERT INTO car (make, model, price) values ('Mercury', 'Solara', '10465.51');
INSERT INTO car (make, model, price) values ('Ford', 'Sierra 2500 HD Crew Cab', '10051.76');
INSERT INTO car (make, model, price) values ('Ford', 'Q', '10007.0');
INSERT INTO car (make, model, price) values ('Chrysler', '3500 Club Coupe', '10047.9');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'LS', '10243.37');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Sonata Hybrid', '10763.32');
INSERT INTO car (make, model, price) values ('Isuzu', '4C', '10642.92');
INSERT INTO car (make, model, price) values ('Ford', 'Lanos', '10010.59');
INSERT INTO car (make, model, price) values ('Chevrolet', '240', '15367.22');
INSERT INTO car (make, model, price) values ('Toyota', 'Cougar', '10001.46');
INSERT INTO car (make, model, price) values ('BMW', 'F250 Regular Cab', '10474.53');
INSERT INTO car (make, model, price) values ('Scion', 'Sonata Plug-in Hybrid', '10715.31');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Sentra', '19917.3');
INSERT INTO car (make, model, price) values ('Toyota', '612 Scaglietti', '51943.09');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Caliber', '10001.38');
INSERT INTO car (make, model, price) values ('Chevrolet', '3500 Crew Cab', '10050.4');
INSERT INTO car (make, model, price) values ('GMC', 'Countryman', '28245.57');
INSERT INTO car (make, model, price) values ('Mercury', 'Malibu', '10834.42');
INSERT INTO car (make, model, price) values ('Chevrolet', '3500 Crew Cab', '35575.75');
INSERT INTO car (make, model, price) values ('MAZDA', 'F150 Super Cab', '10002.65');
INSERT INTO car (make, model, price) values ('Ford', 'Sprinter 2500 Passenger', '63361.84');
INSERT INTO car (make, model, price) values ('Ford', 'Avalanche 2500', '10001.31');
INSERT INTO car (make, model, price) values ('Land Rover', 'Passport', '10009.4');
INSERT INTO car (make, model, price) values ('Ford', 'Sportvan G10', '33521.76');
INSERT INTO car (make, model, price) values ('FIAT', 'Torrent', '30450.32');
INSERT INTO car (make, model, price) values ('Mercury', 'Forte5', '10004.21');
INSERT INTO car (make, model, price) values ('Jaguar', 'Metris Cargo', '10059.91');
INSERT INTO car (make, model, price) values ('Land Rover', '7 Series', '10009.28');
INSERT INTO car (make, model, price) values ('Lincoln', 'Elantra GT', '60984.64');
INSERT INTO car (make, model, price) values ('Chevrolet', 'F12berlinetta', '10008.06');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Clarity Fuel Cell', '10003.31');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Crown Victoria', '11833.38');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Rogue', '10053.38');
INSERT INTO car (make, model, price) values ('Toyota', 'Discovery', '17344.3');
INSERT INTO car (make, model, price) values ('Toyota', 'Sportage', '10099.96');
INSERT INTO car (make, model, price) values ('BMW', 'Spark', '10551.28');
INSERT INTO car (make, model, price) values ('Dodge', 'RDX', '10007.86');
INSERT INTO car (make, model, price) values ('GMC', 'Murcielago', '10087.44');
INSERT INTO car (make, model, price) values ('Chevrolet', '500 Abarth', '10095.32');
INSERT INTO car (make, model, price) values ('Suzuki', 'Jetta', '10085.93');
INSERT INTO car (make, model, price) values ('Ferrari', '3-Sep', '10067.28');
INSERT INTO car (make, model, price) values ('Geo', 'Mark VII', '10057.63');
INSERT INTO car (make, model, price) values ('Chevrolet', '7 Series', '19093.26');
INSERT INTO car (make, model, price) values ('smart', 'Suburban 3500HD', '10015.57');
INSERT INTO car (make, model, price) values ('Toyota', 'Sprinter 2500 Cargo', '10627.87');
INSERT INTO car (make, model, price) values ('Cadillac', 'Outback', '10037.1');
INSERT INTO car (make, model, price) values ('Dodge', 'Avalanche 1500', '10001.91');
INSERT INTO car (make, model, price) values ('Cadillac', 'Explorer Sport', '16290.96');
INSERT INTO car (make, model, price) values ('Pontiac', 'DeVille', '10515.17');
INSERT INTO car (make, model, price) values ('Toyota', '190 E', '10005.82');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Impreza', '10003.56');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Savana 2500 Cargo', '86432.94');
INSERT INTO car (make, model, price) values ('Volvo', 'HHR', '10006.35');
INSERT INTO car (make, model, price) values ('Cadillac', 'MAZDA5', '10000.71');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Tacoma Double Cab', '17562.59');
INSERT INTO car (make, model, price) values ('Ford', 'Stealth', '10003.36');
INSERT INTO car (make, model, price) values ('Nissan', 'SC', '17672.14');
INSERT INTO car (make, model, price) values ('Kia', 'Rabbit', '10038.75');
INSERT INTO car (make, model, price) values ('Lincoln', 'Prius', '24680.54');
INSERT INTO car (make, model, price) values ('Chrysler', 'S-Type', '10016.65');
INSERT INTO car (make, model, price) values ('Saab', 'Golf GTI', '10084.04');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Expo', '10780.96');
INSERT INTO car (make, model, price) values ('GMC', 'Bolt EV', '10085.46');
INSERT INTO car (make, model, price) values ('Dodge', 'E-PACE', '103898.89');
INSERT INTO car (make, model, price) values ('Kia', 'Avalanche', '74067.47');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Sequoia', '10008.5');
INSERT INTO car (make, model, price) values ('Toyota', 'Silverado 3500 HD Regular Cab', '109184.14');
INSERT INTO car (make, model, price) values ('Ford', 'Escape', '70568.3');
INSERT INTO car (make, model, price) values ('Nissan', 'X3', '17846.4');
INSERT INTO car (make, model, price) values ('Cadillac', 'Ram Van 2500', '19165.88');
INSERT INTO car (make, model, price) values ('Hyundai', 'Tribute', '10922.86');
INSERT INTO car (make, model, price) values ('Dodge', 'MR2', '109147.32');
INSERT INTO car (make, model, price) values ('Ford', '5 Series', '10781.46');
INSERT INTO car (make, model, price) values ('Mercury', 'MDX', '10374.83');
INSERT INTO car (make, model, price) values ('Chevrolet', 'G-Class', '10013.86');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Mercedes-AMG GLE Coupe', '10094.54');
INSERT INTO car (make, model, price) values ('GMC', '626', '10009.87');
INSERT INTO car (make, model, price) values ('Buick', 'Econoline E250 Cargo', '10052.67');
INSERT INTO car (make, model, price) values ('Cadillac', 'Trooper', '10047.36');
INSERT INTO car (make, model, price) values ('Volvo', 'Astro Cargo', '10984.76');
INSERT INTO car (make, model, price) values ('Porsche', 'Safari Cargo', '10003.72');
INSERT INTO car (make, model, price) values ('Honda', 'Yukon', '10047.5');
INSERT INTO car (make, model, price) values ('Ford', '2500 HD Club Coupe', '50526.47');
INSERT INTO car (make, model, price) values ('Ford', 'Silverado 3500 Extended Cab', '10002.29');
INSERT INTO car (make, model, price) values ('Dodge', '2500 HD Extended Cab', '10006.18');
INSERT INTO car (make, model, price) values ('Isuzu', 'FX', '10007.6');
INSERT INTO car (make, model, price) values ('Ford', 'S90', '10004.74');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Sonic', '10803.31');
INSERT INTO car (make, model, price) values ('Ford', 'Niro', '15347.49');
INSERT INTO car (make, model, price) values ('BMW', 'Ram Wagon 3500', '10080.03');
INSERT INTO car (make, model, price) values ('GMC', 'Dakota Extended Cab', '27397.11');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'D150 Regular Cab', '10033.01');
INSERT INTO car (make, model, price) values ('Kia', 'Sierra 3500 Crew Cab', '10588.75');
INSERT INTO car (make, model, price) values ('Ford', 'Tribute', '10006.29');
INSERT INTO car (make, model, price) values ('Ford', 'E-Class', '70361.2');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Wraith', '10049.38');
INSERT INTO car (make, model, price) values ('smart', 'Sierra (Classic) 2500 HD Regular Cab', '10005.55');
INSERT INTO car (make, model, price) values ('Toyota', 'Fit', '43054.9');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Frontier Crew Cab', '10094.8');
INSERT INTO car (make, model, price) values ('Suzuki', 'Quattro', '10036.68');
INSERT INTO car (make, model, price) values ('Oldsmobile', '3500 Crew Cab', '11575.32');
INSERT INTO car (make, model, price) values ('Acura', 'Cabriolet', '10046.0');
INSERT INTO car (make, model, price) values ('GMC', 'DeVille', '10015.34');
INSERT INTO car (make, model, price) values ('Ford', 'Sonoma Regular Cab', '10470.63');
INSERT INTO car (make, model, price) values ('Acura', 'Golf', '16415.41');
INSERT INTO car (make, model, price) values ('Dodge', '2500 Club Coupe', '14868.07');
INSERT INTO car (make, model, price) values ('Volvo', 'F250 Super Duty Crew Cab', '45270.27');
INSERT INTO car (make, model, price) values ('Oldsmobile', 'Expedition', '15625.38');
INSERT INTO car (make, model, price) values ('Volvo', 'Cayenne', '18576.58');
INSERT INTO car (make, model, price) values ('Ford', 'Vantage', '17722.19');
INSERT INTO car (make, model, price) values ('Dodge', 'Regular Cab', '10949.7');
INSERT INTO car (make, model, price) values ('Ford', 'Encore', '30180.46');
INSERT INTO car (make, model, price) values ('Nissan', 'Navigator', '13310.28');
INSERT INTO car (make, model, price) values ('Cadillac', 'Town & Country', '10048.66');
INSERT INTO car (make, model, price) values ('Jeep', 'S4', '10002.92');
INSERT INTO car (make, model, price) values ('Ford', 'F350 Super Duty Super Cab', '10540.06');
INSERT INTO car (make, model, price) values ('Chrysler', 'Navajo', '97363.98');
INSERT INTO car (make, model, price) values ('Toyota', 'Sonoma Crew Cab', '10474.58');
INSERT INTO car (make, model, price) values ('Dodge', 'Grand Prix', '17679.17');
INSERT INTO car (make, model, price) values ('GMC', 'Golf', '15667.11');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Firebird', '10743.41');
INSERT INTO car (make, model, price) values ('Honda', 'Corvette', '74064.58');
INSERT INTO car (make, model, price) values ('GMC', 'Dakota Quad Cab', '10028.54');
INSERT INTO car (make, model, price) values ('Kia', 'fortwo electric drive', '10008.35');
INSERT INTO car (make, model, price) values ('BMW', 'Rogue', '10060.73');
INSERT INTO car (make, model, price) values ('Subaru', 'Express 1500 Passenger', '10094.83');
INSERT INTO car (make, model, price) values ('Honda', 'Silverado 2500 HD Regular Cab', '10076.74');
INSERT INTO car (make, model, price) values ('FIAT', 'Macan', '13208.62');
INSERT INTO car (make, model, price) values ('Oldsmobile', 'Dakota Regular Cab', '10064.53');
INSERT INTO car (make, model, price) values ('Ford', 'Viper', '19291.8');
INSERT INTO car (make, model, price) values ('MAZDA', 'Vantage', '10137.72');
INSERT INTO car (make, model, price) values ('Alfa Romeo', 'DeVille', '17461.45');
INSERT INTO car (make, model, price) values ('Ford', 'H1', '10002.05');
INSERT INTO car (make, model, price) values ('Mercury', 'Maxima', '10179.7');
INSERT INTO car (make, model, price) values ('Rolls-Royce', 'Century', '10617.56');
INSERT INTO car (make, model, price) values ('Jaguar', 'Grand Vitara', '10002.49');
INSERT INTO car (make, model, price) values ('Chrysler', 'cube', '91946.39');
INSERT INTO car (make, model, price) values ('MAZDA', 'Sebring', '10007.64');
INSERT INTO car (make, model, price) values ('Toyota', 'Edge', '95774.07');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Tundra CrewMax', '13175.55');
INSERT INTO car (make, model, price) values ('Ford', 'Spirit', '10284.19');
INSERT INTO car (make, model, price) values ('Buick', 'F250 Super Duty Regular Cab', '10008.26');
INSERT INTO car (make, model, price) values ('Lexus', 'Town & Country', '14657.0');
INSERT INTO car (make, model, price) values ('Hyundai', 'Outlander', '10041.85');
INSERT INTO car (make, model, price) values ('Audi', 'CL-Class', '10000.41');
INSERT INTO car (make, model, price) values ('Ford', 'GLC', '68446.3');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Civic', '10492.61');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Tucson', '10884.64');
INSERT INTO car (make, model, price) values ('GMC', 'RL', '10005.25');
INSERT INTO car (make, model, price) values ('Land Rover', '5-Sep', '10014.27');
INSERT INTO car (make, model, price) values ('INFINITI', '1500 Extended Cab', '13686.62');
INSERT INTO car (make, model, price) values ('Lexus', 'Spark', '10598.23');
INSERT INTO car (make, model, price) values ('Toyota', 'Lancer', '10003.74');
INSERT INTO car (make, model, price) values ('INFINITI', 'Sierra (Classic) 3500 Extended Cab', '10767.51');
INSERT INTO car (make, model, price) values ('GMC', 'Tercel', '10002.19');
INSERT INTO car (make, model, price) values ('Dodge', 'S-Class', '10089.27');
INSERT INTO car (make, model, price) values ('Lexus', 'Econoline E250 Cargo', '10082.11');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Matrix', '10475.4');
INSERT INTO car (make, model, price) values ('GMC', 'C-MAX Hybrid', '10895.42');
INSERT INTO car (make, model, price) values ('BMW', 'Mustang', '10006.69');
INSERT INTO car (make, model, price) values ('GMC', 'Cutlass Ciera', '10087.36');
INSERT INTO car (make, model, price) values ('GMC', 'CLS-Class', '23829.04');
INSERT INTO car (make, model, price) values ('Hyundai', '1500 Regular Cab', '10043.43');
INSERT INTO car (make, model, price) values ('Nissan', '8 Series', '10106.21');
INSERT INTO car (make, model, price) values ('Chrysler', 'CLS-Class', '10187.56');
INSERT INTO car (make, model, price) values ('Toyota', 'Rio', '56166.72');
INSERT INTO car (make, model, price) values ('Hyundai', 'F250 Super Duty Super Cab', '10829.7');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Express 3500 Passenger', '10009.68');
INSERT INTO car (make, model, price) values ('GMC', 'Express 3500 Passenger', '10008.45');
INSERT INTO car (make, model, price) values ('Kia', 'MX-5 Miata', '10009.33');
INSERT INTO car (make, model, price) values ('Nissan', 'RAV4', '10086.66');
INSERT INTO car (make, model, price) values ('Toyota', 'Trooper', '10461.13');
INSERT INTO car (make, model, price) values ('Chrysler', 'Passport', '10018.94');
INSERT INTO car (make, model, price) values ('Subaru', 'VehiCROSS', '16478.6');
INSERT INTO car (make, model, price) values ('Dodge', 'Ram 3500 Regular Cab', '10000.57');
INSERT INTO car (make, model, price) values ('Ford', 'NV3500 HD Cargo', '104588.29');
INSERT INTO car (make, model, price) values ('Ford', 'Mustang', '10083.43');
INSERT INTO car (make, model, price) values ('Lexus', 'LeSabre', '16443.32');
INSERT INTO car (make, model, price) values ('Land Rover', 'Diamante', '33490.79');
INSERT INTO car (make, model, price) values ('Ford', 'MPV', '12487.49');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', '1 Series', '10003.86');
INSERT INTO car (make, model, price) values ('INFINITI', 'Spider', '17986.77');
INSERT INTO car (make, model, price) values ('Nissan', 'Terrain', '10002.88');
INSERT INTO car (make, model, price) values ('Suzuki', 'Astro Passenger', '10875.1');
INSERT INTO car (make, model, price) values ('Mercury', 'Frontier Regular Cab', '10097.42');
INSERT INTO car (make, model, price) values ('GMC', '2500 Extended Cab', '10740.42');
INSERT INTO car (make, model, price) values ('Volvo', 'Villager', '10082.73');
INSERT INTO car (make, model, price) values ('Dodge', 'Breeze', '59163.39');
INSERT INTO car (make, model, price) values ('Toyota', 'F250 Regular Cab', '94329.56');
INSERT INTO car (make, model, price) values ('Chevrolet', 'King Cab', '12693.75');
INSERT INTO car (make, model, price) values ('Volvo', 'Sebring', '10545.51');
INSERT INTO car (make, model, price) values ('Ford', 'Verano', '10007.81');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'QX80', '90549.85');
INSERT INTO car (make, model, price) values ('GMC', 'RAV4', '11714.0');
INSERT INTO car (make, model, price) values ('Land Rover', 'Silverado 1500 Extended Cab', '10004.83');
INSERT INTO car (make, model, price) values ('Toyota', 'Suburban 3500HD', '10053.39');
INSERT INTO car (make, model, price) values ('Acura', 'DB9', '10002.84');
INSERT INTO car (make, model, price) values ('Ford', 'Envoy', '10063.77');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Continental', '13072.71');
INSERT INTO car (make, model, price) values ('GMC', 'Montero Sport', '10638.91');
INSERT INTO car (make, model, price) values ('BMW', 'Tiburon', '43240.45');
INSERT INTO car (make, model, price) values ('Mercury', 'Spark', '10002.94');
INSERT INTO car (make, model, price) values ('Chevrolet', 'E-Class', '10009.91');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Mercedes-AMG C-Class', '27970.05');
INSERT INTO car (make, model, price) values ('Dodge', 'Yaris Hatchback', '85875.09');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Swift', '10005.42');
INSERT INTO car (make, model, price) values ('MINI', '3 Series', '20724.68');
INSERT INTO car (make, model, price) values ('GMC', 'Sprinter 2500 Crew', '10060.99');
INSERT INTO car (make, model, price) values ('Chrysler', 'Yukon XL 1500', '10000.71');
INSERT INTO car (make, model, price) values ('Nissan', 'Bolt EV', '10822.92');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Optima', '32388.05');
INSERT INTO car (make, model, price) values ('Freightliner', 'Passat', '10756.18');
INSERT INTO car (make, model, price) values ('BMW', 'Dakota Extended Cab', '15620.74');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Grand Prix', '19243.73');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Dakota Regular Cab', '10715.82');
INSERT INTO car (make, model, price) values ('Dodge', 'Model 3', '10971.58');
INSERT INTO car (make, model, price) values ('Acura', 'Evora 400', '14469.43');
INSERT INTO car (make, model, price) values ('Pontiac', 'F150 SuperCrew Cab', '10082.62');
INSERT INTO car (make, model, price) values ('Toyota', 'Frontier Crew Cab', '10003.87');
INSERT INTO car (make, model, price) values ('Toyota', 'Ridgeline', '10009.02');
INSERT INTO car (make, model, price) values ('Volvo', 'M-Class', '10090.58');
INSERT INTO car (make, model, price) values ('Maserati', '3 Series', '10009.61');
INSERT INTO car (make, model, price) values ('Chrysler', 'T100 Regular Cab', '14932.9');
INSERT INTO car (make, model, price) values ('Lotus', 'Metris Passenger', '10002.18');
INSERT INTO car (make, model, price) values ('Audi', 'Summit', '10458.18');
INSERT INTO car (make, model, price) values ('Honda', 'Sequoia', '12200.33');
INSERT INTO car (make, model, price) values ('Ford', 'Safari Passenger', '10006.22');
INSERT INTO car (make, model, price) values ('Dodge', 'Hombre Regular Cab', '10012.86');
INSERT INTO car (make, model, price) values ('MAZDA', 'Savana 2500 Passenger', '10929.2');
INSERT INTO car (make, model, price) values ('Audi', 'Ram Wagon 3500', '10003.33');
INSERT INTO car (make, model, price) values ('Jaguar', 'X3', '13851.0');
INSERT INTO car (make, model, price) values ('Ford', 'Jimmy', '76221.85');
INSERT INTO car (make, model, price) values ('Cadillac', 'SC', '10299.67');
INSERT INTO car (make, model, price) values ('Hyundai', 'Enclave', '13830.53');
INSERT INTO car (make, model, price) values ('Ferrari', 'JUKE', '10064.66');
INSERT INTO car (make, model, price) values ('Land Rover', 'Grand Caravan Passenger', '10977.11');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', '2500 Regular Cab', '10052.55');
INSERT INTO car (make, model, price) values ('Buick', 'Savana 3500 Cargo', '10448.84');
INSERT INTO car (make, model, price) values ('Kia', 'R32', '17463.55');
INSERT INTO car (make, model, price) values ('GMC', 'SC', '10094.84');
INSERT INTO car (make, model, price) values ('BMW', 'Sonata Plug-in Hybrid', '19002.42');
INSERT INTO car (make, model, price) values ('MAZDA', 'Compass', '14674.46');
INSERT INTO car (make, model, price) values ('Volkswagen', 'California', '10032.85');
INSERT INTO car (make, model, price) values ('Honda', 'M2', '10008.1');
INSERT INTO car (make, model, price) values ('Freightliner', 'Leganza', '10074.77');
INSERT INTO car (make, model, price) values ('Ford', 'Sierra 1500 Regular Cab', '10235.98');
INSERT INTO car (make, model, price) values ('Mercury', 'Expedition', '10810.2');
INSERT INTO car (make, model, price) values ('GMC', 'Silhouette', '10006.49');
INSERT INTO car (make, model, price) values ('Mercury', 'Express 1500 Cargo', '10006.7');
INSERT INTO car (make, model, price) values ('Jaguar', 'WRX', '10003.43');
INSERT INTO car (make, model, price) values ('MAZDA', '7 Series', '10936.22');
INSERT INTO car (make, model, price) values ('MAZDA', 'GT-R', '29858.6');
INSERT INTO car (make, model, price) values ('Jeep', 'Santa Fe XL', '10008.61');
INSERT INTO car (make, model, price) values ('Volkswagen', 'X5', '10023.75');
INSERT INTO car (make, model, price) values ('Ford', 'Wrangler', '13195.95');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Odyssey', '10886.35');
INSERT INTO car (make, model, price) values ('Ford', 'Laser', '27758.88');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Pilot', '60582.1');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Equinox', '10025.53');
INSERT INTO car (make, model, price) values ('GMC', 'Tribeca', '10018.5');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Previa', '13766.79');
INSERT INTO car (make, model, price) values ('Buick', 'Express 1500 Passenger', '17617.87');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Wrangler', '81486.41');
INSERT INTO car (make, model, price) values ('Hyundai', 'S-Series', '10673.13');
INSERT INTO car (make, model, price) values ('Honda', 'Milan', '62569.6');
INSERT INTO car (make, model, price) values ('Ford', 'Avalon Hybrid', '10868.81');
INSERT INTO car (make, model, price) values ('Suzuki', 'XC90', '10085.26');
INSERT INTO car (make, model, price) values ('Nissan', 'xB', '10540.52');
INSERT INTO car (make, model, price) values ('Hyundai', 'X6', '10868.9');
INSERT INTO car (make, model, price) values ('Dodge', 'Accent', '10005.47');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Escalade', '16066.62');
INSERT INTO car (make, model, price) values ('Jeep', 'TT', '11972.54');
INSERT INTO car (make, model, price) values ('Freightliner', 'GX', '19653.99');
INSERT INTO car (make, model, price) values ('Volkswagen', '4C', '10005.6');
INSERT INTO car (make, model, price) values ('Toyota', 'Z4 M', '102654.68');
INSERT INTO car (make, model, price) values ('Toyota', '2500 Club Coupe', '10006.08');
INSERT INTO car (make, model, price) values ('Mercury', 'Ram 50 Regular Cab', '10191.15');
INSERT INTO car (make, model, price) values ('Land Rover', 'Suburban 2500', '86157.45');
INSERT INTO car (make, model, price) values ('INFINITI', 'Spirit', '19165.77');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Matrix', '10020.59');
INSERT INTO car (make, model, price) values ('Hyundai', 'Savana 1500 Passenger', '10019.78');
INSERT INTO car (make, model, price) values ('Dodge', 'Astro Cargo', '88911.46');
INSERT INTO car (make, model, price) values ('Lexus', 'Ram 1500 Regular Cab', '18742.6');
INSERT INTO car (make, model, price) values ('Chrysler', 'Tribeca', '10062.13');
INSERT INTO car (make, model, price) values ('Geo', 'Rogue', '10031.32');
INSERT INTO car (make, model, price) values ('Ford', '1500 Regular Cab', '10008.47');
INSERT INTO car (make, model, price) values ('Hyundai', 'Sequoia', '10008.69');
INSERT INTO car (make, model, price) values ('MAZDA', 'Venue', '10022.66');
INSERT INTO car (make, model, price) values ('Toyota', 'F150 Super Cab', '10005.97');
INSERT INTO car (make, model, price) values ('Rolls-Royce', 'New Yorker', '66724.54');
INSERT INTO car (make, model, price) values ('Ford', 'Grand Cherokee', '10000.46');
INSERT INTO car (make, model, price) values ('GMC', 'Elantra', '14323.94');
INSERT INTO car (make, model, price) values ('Mercury', 'GS', '14509.45');
INSERT INTO car (make, model, price) values ('McLaren', 'MPV', '10059.93');
INSERT INTO car (make, model, price) values ('Hyundai', 'TT', '10344.95');
INSERT INTO car (make, model, price) values ('Toyota', 'Grand Cherokee', '10077.78');
INSERT INTO car (make, model, price) values ('Dodge', 'F350 Super Duty Crew Cab', '91202.76');
INSERT INTO car (make, model, price) values ('Alfa Romeo', 'R32', '10106.88');
INSERT INTO car (make, model, price) values ('Scion', 'Savana 2500 Passenger', '10002.63');
INSERT INTO car (make, model, price) values ('Hyundai', 'Genesis', '85291.68');
INSERT INTO car (make, model, price) values ('Ford', 'Land Cruiser', '96350.53');
INSERT INTO car (make, model, price) values ('Saturn', '2500 Mega Cab', '16332.76');
INSERT INTO car (make, model, price) values ('Ford', 'Range Rover', '10032.19');
INSERT INTO car (make, model, price) values ('Dodge', 'Summit', '10915.3');
INSERT INTO car (make, model, price) values ('FIAT', 'Wrangler Unlimited', '63221.66');
INSERT INTO car (make, model, price) values ('Honda', 'Rogue Select', '10019.64');
INSERT INTO car (make, model, price) values ('Subaru', 'G-Class', '10901.2');
INSERT INTO car (make, model, price) values ('Kia', 'Ram 2500 Quad Cab', '18519.33');
INSERT INTO car (make, model, price) values ('Ford', 'Suburban 1500', '10673.86');
INSERT INTO car (make, model, price) values ('Chevrolet', 'CL-Class', '10094.07');
INSERT INTO car (make, model, price) values ('Ford', 'CC', '10397.45');
INSERT INTO car (make, model, price) values ('Toyota', 'Camry', '10030.57');
INSERT INTO car (make, model, price) values ('Toyota', 'iQ', '52131.04');
INSERT INTO car (make, model, price) values ('GMC', 'Aerostar Cargo', '10725.46');
INSERT INTO car (make, model, price) values ('Toyota', 'Savana 2500 Cargo', '10008.1');
INSERT INTO car (make, model, price) values ('Buick', 'Continental', '10006.37');
INSERT INTO car (make, model, price) values ('Volkswagen', 'LS', '10152.5');
INSERT INTO car (make, model, price) values ('Subaru', 'Sierra 2500 HD Crew Cab', '21826.91');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'C70', '76878.36');
INSERT INTO car (make, model, price) values ('Chevrolet', 'GranTurismo', '16958.44');
INSERT INTO car (make, model, price) values ('Lincoln', 'Liberty', '10096.06');
INSERT INTO car (make, model, price) values ('Volvo', 'Reno', '13858.0');
INSERT INTO car (make, model, price) values ('Toyota', 'Envoy', '10084.14');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Caravan Cargo', '14966.58');
INSERT INTO car (make, model, price) values ('Dodge', 'Silverado 3500 HD Crew Cab', '10085.58');
INSERT INTO car (make, model, price) values ('Plymouth', 'XJ', '10006.08');
INSERT INTO car (make, model, price) values ('GMC', 'Blazer', '10004.22');
INSERT INTO car (make, model, price) values ('Honda', 'Nitro', '10000.66');
INSERT INTO car (make, model, price) values ('FIAT', 'RL', '10486.06');
INSERT INTO car (make, model, price) values ('Jaguar', 'Silverado 2500 HD Regular Cab', '102955.42');
INSERT INTO car (make, model, price) values ('Scion', 'Tundra Double Cab', '10061.11');
INSERT INTO car (make, model, price) values ('BMW', 'Camaro', '13906.71');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Yukon XL 2500', '55317.42');
INSERT INTO car (make, model, price) values ('Jeep', 'Sierra 3500 HD Extended Cab', '69808.96');
INSERT INTO car (make, model, price) values ('BMW', 'Titan King Cab', '17324.77');
INSERT INTO car (make, model, price) values ('Ford', 'PT Cruiser', '10066.97');
INSERT INTO car (make, model, price) values ('Ford', 'Stinger', '40343.36');
INSERT INTO car (make, model, price) values ('Honda', 'Expedition EL', '10702.8');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'S60', '10027.35');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Amanti', '10085.94');
INSERT INTO car (make, model, price) values ('Dodge', 'Raider Extended Cab', '10008.15');
INSERT INTO car (make, model, price) values ('Mercury', 'MAZDA6', '67104.88');
INSERT INTO car (make, model, price) values ('Lexus', 'Jetta III', '10036.64');
INSERT INTO car (make, model, price) values ('Volvo', 'CLS-Class', '10389.64');
INSERT INTO car (make, model, price) values ('INFINITI', 'E350 Super Duty Passenger', '27892.92');
INSERT INTO car (make, model, price) values ('Dodge', 'Silverado 2500 HD Regular Cab', '26203.97');
INSERT INTO car (make, model, price) values ('Audi', 'F250 Super Duty Super Cab', '10291.28');
INSERT INTO car (make, model, price) values ('Mercury', 'Sportvan G30', '10085.33');
INSERT INTO car (make, model, price) values ('Ford', 'Land Cruiser', '10703.54');
INSERT INTO car (make, model, price) values ('Porsche', 'Rapide S', '10057.19');
INSERT INTO car (make, model, price) values ('Mercury', 'Silhouette', '10004.31');
INSERT INTO car (make, model, price) values ('Lexus', 'S6', '17201.16');
INSERT INTO car (make, model, price) values ('Acura', '911', '10002.95');
INSERT INTO car (make, model, price) values ('Buick', 'MDX', '10026.13');
INSERT INTO car (make, model, price) values ('Jeep', 'Enclave', '10385.33');
INSERT INTO car (make, model, price) values ('Geo', 'Corolla', '10098.94');
INSERT INTO car (make, model, price) values ('Lincoln', 'L-Series', '15945.48');
INSERT INTO car (make, model, price) values ('Volvo', 'Impala', '10304.94');
INSERT INTO car (make, model, price) values ('Suzuki', 'Continental', '11041.32');
INSERT INTO car (make, model, price) values ('Audi', 'Caravan Passenger', '15509.51');
INSERT INTO car (make, model, price) values ('Toyota', 'Optima', '10007.54');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Equator Extended Cab', '10006.93');
INSERT INTO car (make, model, price) values ('Toyota', 'Ram 1500 Mega Cab', '10007.58');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Outback', '40663.62');
INSERT INTO car (make, model, price) values ('Volkswagen', '3500 Crew Cab', '10904.06');
INSERT INTO car (make, model, price) values ('BMW', 'RX', '10004.26');
INSERT INTO car (make, model, price) values ('Chevrolet', '458 Spider', '10037.26');
INSERT INTO car (make, model, price) values ('Maserati', 'Optima', '34175.04');
INSERT INTO car (make, model, price) values ('BMW', 'Impala', '103646.15');
INSERT INTO car (make, model, price) values ('Dodge', 'Ram 2500 Regular Cab', '10088.93');
INSERT INTO car (make, model, price) values ('GMC', 'QX60', '10318.88');
INSERT INTO car (make, model, price) values ('Audi', 'Ram Van 3500', '10990.84');
INSERT INTO car (make, model, price) values ('Toyota', 'Monte Carlo', '10069.26');
INSERT INTO car (make, model, price) values ('Dodge', 'Ram 1500 Quad Cab', '10004.19');
INSERT INTO car (make, model, price) values ('Bentley', 'Boxster', '10015.27');
INSERT INTO car (make, model, price) values ('Nissan', 'Camry', '74130.94');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Vibe', '10064.09');
INSERT INTO car (make, model, price) values ('GMC', 'GS', '13289.92');
INSERT INTO car (make, model, price) values ('Lexus', 'Colorado Regular Cab', '10003.82');
INSERT INTO car (make, model, price) values ('BMW', 'Astro Passenger', '16475.06');
INSERT INTO car (make, model, price) values ('MAZDA', 'SL-Class', '82052.03');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Quest', '10076.02');
INSERT INTO car (make, model, price) values ('Audi', 'Express 2500 Cargo', '12627.94');
INSERT INTO car (make, model, price) values ('Dodge', 'MKZ', '10290.06');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Rendezvous', '10007.08');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Panamera', '46225.36');
INSERT INTO car (make, model, price) values ('Chevrolet', 'DBS', '10023.41');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Encore', '63508.46');
INSERT INTO car (make, model, price) values ('Plymouth', 'M5', '10006.36');
INSERT INTO car (make, model, price) values ('Genesis', 'Vandura 3500', '10073.0');
INSERT INTO car (make, model, price) values ('Mercury', 'Tacoma Double Cab', '10019.28');
INSERT INTO car (make, model, price) values ('Lexus', 'Cayenne Coupe', '10561.36');
INSERT INTO car (make, model, price) values ('BMW', 'Savana 3500 Passenger', '16595.38');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Cadenza', '10038.89');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Tundra Double Cab', '11503.96');
INSERT INTO car (make, model, price) values ('GMC', 'Aviator', '10069.75');
INSERT INTO car (make, model, price) values ('GMC', 'Rodeo', '46323.22');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'GX', '18734.76');
INSERT INTO car (make, model, price) values ('Maserati', 'Grand Prix', '14349.85');
INSERT INTO car (make, model, price) values ('MINI', '200', '10858.66');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Tacoma Xtracab', '10585.7');
INSERT INTO car (make, model, price) values ('Volkswagen', '3-Sep', '10142.05');
INSERT INTO car (make, model, price) values ('Dodge', 'Xterra', '10930.81');
INSERT INTO car (make, model, price) values ('Nissan', 'Xtra Cab', '10048.55');
INSERT INTO car (make, model, price) values ('Toyota', 'MKZ', '16149.75');
INSERT INTO car (make, model, price) values ('Cadillac', 'King Cab', '42346.61');
INSERT INTO car (make, model, price) values ('INFINITI', 'Compass', '10037.02');
INSERT INTO car (make, model, price) values ('Buick', 'Sprinter WORKER Passenger', '10000.26');
INSERT INTO car (make, model, price) values ('Dodge', 'Yukon XL', '10071.44');
INSERT INTO car (make, model, price) values ('Dodge', 'NV1500 Cargo', '10005.4');
INSERT INTO car (make, model, price) values ('Cadillac', 'A3', '10077.47');
INSERT INTO car (make, model, price) values ('Freightliner', 'Impreza', '10009.29');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'A4', '87732.34');
INSERT INTO car (make, model, price) values ('BMW', 'MPV', '13322.5');
INSERT INTO car (make, model, price) values ('Toyota', 'Sequoia', '83039.4');
INSERT INTO car (make, model, price) values ('Lamborghini', 'I', '87810.07');
INSERT INTO car (make, model, price) values ('Pontiac', 'Genesis Coupe', '18222.62');
INSERT INTO car (make, model, price) values ('Dodge', 'C-Class', '10983.61');
INSERT INTO car (make, model, price) values ('Maybach', 'Mirage', '10001.29');
INSERT INTO car (make, model, price) values ('Dodge', 'Eldorado', '19320.35');
INSERT INTO car (make, model, price) values ('Ford', 'Sportage', '10012.45');
INSERT INTO car (make, model, price) values ('Audi', 'Jetta', '10081.19');
INSERT INTO car (make, model, price) values ('Audi', 'H1', '10003.4');
INSERT INTO car (make, model, price) values ('Suzuki', 'Grand Marquis', '10930.56');
INSERT INTO car (make, model, price) values ('Ford', 'Mirage', '10009.46');
INSERT INTO car (make, model, price) values ('Saab', 'Suburban', '17911.61');
INSERT INTO car (make, model, price) values ('Volvo', 'Prius', '58861.93');
INSERT INTO car (make, model, price) values ('Bentley', 'ES', '10056.24');
INSERT INTO car (make, model, price) values ('Dodge', 'Santa Fe Sport', '16208.78');
INSERT INTO car (make, model, price) values ('Toyota', 'RL', '10081.65');
INSERT INTO car (make, model, price) values ('Audi', 'XTS', '15552.76');
INSERT INTO car (make, model, price) values ('Cadillac', 'Rio', '11770.04');
INSERT INTO car (make, model, price) values ('Suzuki', 'C70', '17333.62');
INSERT INTO car (make, model, price) values ('Toyota', 'V50', '10706.5');
INSERT INTO car (make, model, price) values ('Jeep', 'Pathfinder', '10678.76');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Storm', '10002.63');
INSERT INTO car (make, model, price) values ('Chrysler', 'Taurus', '10570.7');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'RX', '10022.17');
INSERT INTO car (make, model, price) values ('Maserati', 'Flying Spur', '10058.85');
INSERT INTO car (make, model, price) values ('Audi', 'Galant', '13923.5');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'M6', '10003.59');
INSERT INTO car (make, model, price) values ('Nissan', 'Sierra 2500 HD Extended Cab', '10315.58');
INSERT INTO car (make, model, price) values ('Scion', '5 Series', '10046.43');
INSERT INTO car (make, model, price) values ('Audi', 'Continental', '10824.71');
INSERT INTO car (make, model, price) values ('Alfa Romeo', 'Envoy', '10009.18');
INSERT INTO car (make, model, price) values ('Toyota', 'Endeavor', '10068.85');
INSERT INTO car (make, model, price) values ('Hyundai', 'G', '10203.43');
INSERT INTO car (make, model, price) values ('Dodge', 'QX', '10080.26');
INSERT INTO car (make, model, price) values ('Isuzu', 'Dakota Quad Cab', '16113.35');
INSERT INTO car (make, model, price) values ('Ram', 'Armada', '10652.6');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Paseo', '10004.58');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Sierra 3500 HD Regular Cab', '10083.53');
INSERT INTO car (make, model, price) values ('Chrysler', 'Grand Cherokee', '12236.16');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'fortwo', '11760.51');
INSERT INTO car (make, model, price) values ('Mercury', 'Tucson Fuel Cell', '10001.07');
INSERT INTO car (make, model, price) values ('Nissan', 'CX-9', '10032.27');
INSERT INTO car (make, model, price) values ('Hyundai', 'Sonoma Club Coupe Cab', '10042.78');
INSERT INTO car (make, model, price) values ('Acura', 'CLS-Class', '18242.41');
INSERT INTO car (make, model, price) values ('BMW', 'Versa', '10694.28');
INSERT INTO car (make, model, price) values ('Porsche', 'Crown Victoria', '10077.24');
INSERT INTO car (make, model, price) values ('INFINITI', 'Azera', '10087.54');
INSERT INTO car (make, model, price) values ('Toyota', 'Commander', '10735.97');
INSERT INTO car (make, model, price) values ('Subaru', 'MX-5 Miata', '12317.93');
INSERT INTO car (make, model, price) values ('Ford', '1500 Regular Cab', '10002.68');
INSERT INTO car (make, model, price) values ('Toyota', 'Sierra 3500 Crew Cab', '50689.8');
INSERT INTO car (make, model, price) values ('Toyota', '1500 Classic Regular Cab', '10240.19');
INSERT INTO car (make, model, price) values ('Lincoln', 'Monte Carlo', '10999.77');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Encore', '10004.11');
INSERT INTO car (make, model, price) values ('Plymouth', 'D150 Regular Cab', '13017.76');
INSERT INTO car (make, model, price) values ('BMW', 'Colorado Crew Cab', '44843.74');
INSERT INTO car (make, model, price) values ('Honda', 'Phantom', '10462.32');
INSERT INTO car (make, model, price) values ('Dodge', 'Outback', '106750.26');
INSERT INTO car (make, model, price) values ('Audi', 'Prius v', '16751.33');
INSERT INTO car (make, model, price) values ('Chevrolet', 'NV1500 Cargo', '25915.98');
INSERT INTO car (make, model, price) values ('Ford', 'Tacoma Access Cab', '10005.26');
INSERT INTO car (make, model, price) values ('Toyota', 'SLK-Class', '13251.94');
INSERT INTO car (make, model, price) values ('Ford', 'C30', '107090.26');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Ram 1500 Regular Cab', '35656.36');
INSERT INTO car (make, model, price) values ('GMC', 'LR2', '10003.95');
INSERT INTO car (make, model, price) values ('Ford', 'JUKE', '10067.21');
INSERT INTO car (make, model, price) values ('Lincoln', 'Savana 2500 Cargo', '63239.91');
INSERT INTO car (make, model, price) values ('GMC', 'CT6-V', '10008.95');
INSERT INTO car (make, model, price) values ('Nissan', 'Aurora', '10004.41');
INSERT INTO car (make, model, price) values ('Ford', 'R32', '83617.86');
INSERT INTO car (make, model, price) values ('Dodge', 'Sierra 3500 HD Extended Cab', '83197.92');
INSERT INTO car (make, model, price) values ('Lincoln', 'Odyssey', '10001.98');
INSERT INTO car (make, model, price) values ('Volvo', 'Protege', '10663.89');
INSERT INTO car (make, model, price) values ('Lexus', 'Roadster', '13082.67');
INSERT INTO car (make, model, price) values ('Volvo', 'Frontier King Cab', '10020.44');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Roadmaster', '10691.4');
INSERT INTO car (make, model, price) values ('Dodge', 'HR-V', '13357.8');
INSERT INTO car (make, model, price) values ('Ford', 'Mulsanne', '10003.72');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'C-Class', '10848.89');
INSERT INTO car (make, model, price) values ('Lincoln', 'GR Supra', '10084.07');
INSERT INTO car (make, model, price) values ('BMW', 'Accord Hybrid', '10006.24');
INSERT INTO car (make, model, price) values ('INFINITI', 'Quest', '10955.03');
INSERT INTO car (make, model, price) values ('Chevrolet', 'I-PACE', '10030.95');
INSERT INTO car (make, model, price) values ('Ford', 'X5', '17613.97');
INSERT INTO car (make, model, price) values ('Hyundai', 'Cherokee', '22078.67');
INSERT INTO car (make, model, price) values ('Ford', '4Runner', '10001.76');
INSERT INTO car (make, model, price) values ('Dodge', 'F250 Regular Cab', '10009.04');
INSERT INTO car (make, model, price) values ('Volkswagen', 'MX-6', '10045.52');
INSERT INTO car (make, model, price) values ('BMW', 'CR-V', '10000.36');
INSERT INTO car (make, model, price) values ('Kia', 'F250 Super Duty Regular Cab', '10423.12');
INSERT INTO car (make, model, price) values ('Ford', 'Armada', '103436.29');
INSERT INTO car (make, model, price) values ('Subaru', 'Windstar Passenger', '10000.44');
INSERT INTO car (make, model, price) values ('Audi', 'GLA', '10360.48');
INSERT INTO car (make, model, price) values ('BMW', 'California', '58360.27');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Envision', '80924.42');
INSERT INTO car (make, model, price) values ('Toyota', 'S70', '81405.69');
INSERT INTO car (make, model, price) values ('Chevrolet', 'MDX', '17210.91');
INSERT INTO car (make, model, price) values ('GMC', 'Silverado 2500 HD Regular Cab', '10091.07');
INSERT INTO car (make, model, price) values ('Lincoln', 'A6', '10004.46');
INSERT INTO car (make, model, price) values ('Toyota', '3 Series', '16556.07');
INSERT INTO car (make, model, price) values ('Honda', 'i-MiEV', '80211.81');
INSERT INTO car (make, model, price) values ('Ford', 'B-Series Extended Cab', '10007.41');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Forester', '10926.61');
INSERT INTO car (make, model, price) values ('MAZDA', 'GL-Class', '10009.0');
INSERT INTO car (make, model, price) values ('INFINITI', 'Savana 2500 Passenger', '10067.15');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Rio', '43788.54');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Hombre Spacecab', '12622.6');
INSERT INTO car (make, model, price) values ('Jeep', 'Silverado 1500 Double Cab', '12715.39');
INSERT INTO car (make, model, price) values ('Volkswagen', 'NV2500 HD Cargo', '72007.64');
INSERT INTO car (make, model, price) values ('Volvo', '190 E', '10055.23');
INSERT INTO car (make, model, price) values ('Dodge', 'Sierra 3500 HD Extended Cab', '10000.27');
INSERT INTO car (make, model, price) values ('Ford', 'Galant', '10563.54');
INSERT INTO car (make, model, price) values ('Ford', 'SLK-Class', '10003.1');
INSERT INTO car (make, model, price) values ('GMC', 'Azera', '10739.68');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Sonata', '10053.71');
INSERT INTO car (make, model, price) values ('Freightliner', 'Tahoe', '104063.47');
INSERT INTO car (make, model, price) values ('Honda', 'Ram Wagon 2500', '26179.78');
INSERT INTO car (make, model, price) values ('Nissan', 'Ghost', '10006.5');
INSERT INTO car (make, model, price) values ('Ford', 'Park Avenue', '65977.58');
INSERT INTO car (make, model, price) values ('Nissan', 'E350 Super Duty Passenger', '10020.31');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Savana 2500 Cargo', '10244.76');
INSERT INTO car (make, model, price) values ('Acura', 'Mercedes-AMG GLC', '10008.7');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Yukon XL', '16752.99');
INSERT INTO car (make, model, price) values ('Audi', 'A3 Sportback e-tron', '10008.82');
INSERT INTO car (make, model, price) values ('Mitsubishi', '350Z', '18658.73');
INSERT INTO car (make, model, price) values ('GMC', 'XC60', '10557.34');
INSERT INTO car (make, model, price) values ('BMW', 'Fusion', '38600.69');
INSERT INTO car (make, model, price) values ('Jeep', 'S80', '10000.18');
INSERT INTO car (make, model, price) values ('Ford', 'Swift', '91376.24');
INSERT INTO car (make, model, price) values ('Lincoln', '370Z', '10257.73');
INSERT INTO car (make, model, price) values ('Ram', 'Montero Sport', '10077.49');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Explorer', '21145.94');
INSERT INTO car (make, model, price) values ('Volvo', 'Rogue', '16815.14');
INSERT INTO car (make, model, price) values ('GMC', 'FR-S', '10089.97');
INSERT INTO car (make, model, price) values ('GMC', 'RAV4', '10006.96');
INSERT INTO car (make, model, price) values ('Plymouth', 'CL', '10024.63');
INSERT INTO car (make, model, price) values ('Maserati', 'Durango', '52239.36');
INSERT INTO car (make, model, price) values ('INFINITI', 'ILX', '69436.42');
INSERT INTO car (make, model, price) values ('BMW', 'Odyssey', '15701.51');
INSERT INTO car (make, model, price) values ('Hyundai', 'Envoy XL', '19842.66');
INSERT INTO car (make, model, price) values ('INFINITI', 'Five Hundred', '15457.09');
INSERT INTO car (make, model, price) values ('BMW', 'Azera', '10092.43');
INSERT INTO car (make, model, price) values ('Cadillac', 'Cayenne', '10006.5');
INSERT INTO car (make, model, price) values ('Ford', '6 Series', '31931.2');
INSERT INTO car (make, model, price) values ('Ford', 'Titan Crew Cab', '12581.11');
INSERT INTO car (make, model, price) values ('Lexus', 'Tundra Regular Cab', '10080.44');
INSERT INTO car (make, model, price) values ('Ford', 'DTS', '13958.95');
INSERT INTO car (make, model, price) values ('Chevrolet', 'MAZDA3', '16607.45');
INSERT INTO car (make, model, price) values ('smart', 'D250 Regular Cab', '10791.1');
INSERT INTO car (make, model, price) values ('BMW', 'Silverado 2500 HD Regular Cab', '17538.96');
INSERT INTO car (make, model, price) values ('Maybach', 'Tiguan Limited', '10061.67');
INSERT INTO car (make, model, price) values ('Ram', 'Sentra', '19494.15');
INSERT INTO car (make, model, price) values ('Lexus', 'Prius', '10053.46');
INSERT INTO car (make, model, price) values ('Lexus', 'Fiesta', '10009.57');
INSERT INTO car (make, model, price) values ('Toyota', 'Crown Victoria', '10685.09');
INSERT INTO car (make, model, price) values ('Jeep', 'Savana 3500 Cargo', '10009.08');
INSERT INTO car (make, model, price) values ('Lexus', '500e', '10086.93');
INSERT INTO car (make, model, price) values ('Chrysler', 'X1', '10002.44');
INSERT INTO car (make, model, price) values ('Hyundai', 'Sierra (Classic) 3500 Extended Cab', '10448.73');
INSERT INTO car (make, model, price) values ('Ford', 'Silverado 1500 Extended Cab', '46867.21');
INSERT INTO car (make, model, price) values ('Mercury', '300', '10069.48');
INSERT INTO car (make, model, price) values ('Cadillac', 'CLK-Class', '10003.94');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Yukon XL', '35604.65');
INSERT INTO car (make, model, price) values ('GMC', 'Jetta (New)', '10975.95');
INSERT INTO car (make, model, price) values ('Jeep', 'TT', '92706.94');
INSERT INTO car (make, model, price) values ('Nissan', 'New Beetle', '10002.88');
INSERT INTO car (make, model, price) values ('Subaru', 'Canyon Extended Cab', '106508.13');
INSERT INTO car (make, model, price) values ('Volvo', '3500 Regular Cab', '74126.02');
INSERT INTO car (make, model, price) values ('Dodge', 'Ram Wagon 2500', '19983.7');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Fusion', '10004.1');
INSERT INTO car (make, model, price) values ('MAZDA', 'Camaro', '39916.11');
INSERT INTO car (make, model, price) values ('Aston Martin', 'XJ', '12554.15');
INSERT INTO car (make, model, price) values ('Dodge', 'S6', '10099.9');
INSERT INTO car (make, model, price) values ('Toyota', 'Aspen', '79039.21');
INSERT INTO car (make, model, price) values ('Honda', 'allroad', '16762.33');
INSERT INTO car (make, model, price) values ('BMW', 'Odyssey', '11854.56');
INSERT INTO car (make, model, price) values ('Ford', 'C-Class', '10014.83');
INSERT INTO car (make, model, price) values ('Toyota', 'A8', '10008.68');
INSERT INTO car (make, model, price) values ('Dodge', '2500 Club Coupe', '10008.46');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Mercedes-Maybach S-Class', '106267.64');
INSERT INTO car (make, model, price) values ('GMC', 'A8', '10383.56');
INSERT INTO car (make, model, price) values ('Ferrari', 'Civic', '14305.69');
INSERT INTO car (make, model, price) values ('Ford', 'B-Series Extended Cab', '12914.62');
INSERT INTO car (make, model, price) values ('Lexus', 'Grand Marquis', '63994.78');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Mercedes-AMG S-Class', '10007.71');
INSERT INTO car (make, model, price) values ('Acura', '2500 Extended Cab', '10070.08');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Levante', '10416.43');
INSERT INTO car (make, model, price) values ('Toyota', 'Sunfire', '10002.56');
INSERT INTO car (make, model, price) values ('Toyota', 'NSX', '10000.43');
INSERT INTO car (make, model, price) values ('GMC', 'G', '40209.54');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Rally Wagon G3500', '10005.35');
INSERT INTO car (make, model, price) values ('Nissan', 'Silverado 2500 HD Extended Cab', '77642.16');
INSERT INTO car (make, model, price) values ('Ford', 'Savana 1500 Cargo', '10053.43');
INSERT INTO car (make, model, price) values ('Hyundai', 'H1', '18533.3');
INSERT INTO car (make, model, price) values ('Suzuki', 'Mountaineer', '10036.18');
INSERT INTO car (make, model, price) values ('Toyota', '3500 Regular Cab', '10852.97');
INSERT INTO car (make, model, price) values ('GMC', '1500 Crew Cab', '90392.8');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Aerostar Passenger', '10051.64');
INSERT INTO car (make, model, price) values ('Cadillac', '2500 Crew Cab', '10024.35');
INSERT INTO car (make, model, price) values ('Dodge', '626', '19861.64');
INSERT INTO car (make, model, price) values ('Aston Martin', 'i3', '10219.91');
INSERT INTO car (make, model, price) values ('Ford', 'MPV', '10021.96');
INSERT INTO car (make, model, price) values ('Audi', 'Liberty', '10004.77');
INSERT INTO car (make, model, price) values ('Nissan', 'Sierra 3500 Extended Cab', '10004.83');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Montero', '10048.1');
INSERT INTO car (make, model, price) values ('GMC', 'Silverado 1500 Extended Cab', '10029.69');
INSERT INTO car (make, model, price) values ('Chevrolet', 'GT-R', '27518.4');
INSERT INTO car (make, model, price) values ('Honda', 'TITAN XD King Cab', '10037.2');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Relay', '10004.32');
INSERT INTO car (make, model, price) values ('Land Rover', 'G', '10090.9');
INSERT INTO car (make, model, price) values ('Honda', 'Corolla', '10006.64');
INSERT INTO car (make, model, price) values ('Pontiac', 'Accord', '12011.09');
INSERT INTO car (make, model, price) values ('MINI', 'Silverado 2500 HD Crew Cab', '13717.48');
INSERT INTO car (make, model, price) values ('BMW', 'Cherokee', '10089.3');
INSERT INTO car (make, model, price) values ('BMW', 'Ram Van 3500', '12877.82');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Yukon XL 1500', '10318.71');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Tiburon', '10080.41');
INSERT INTO car (make, model, price) values ('Dodge', 'Savana 3500 Passenger', '19282.37');
INSERT INTO car (make, model, price) values ('Audi', 'Q70', '10010.93');
INSERT INTO car (make, model, price) values ('Toyota', 'M3', '10008.59');
INSERT INTO car (make, model, price) values ('Chrysler', 'Samurai', '10268.43');
INSERT INTO car (make, model, price) values ('Pontiac', 'Silverado 1500 Regular Cab', '15850.2');
INSERT INTO car (make, model, price) values ('Nissan', 'Express 2500 Passenger', '66103.4');
INSERT INTO car (make, model, price) values ('Dodge', 'Sequoia', '10052.18');
INSERT INTO car (make, model, price) values ('Audi', 'Impreza', '12735.08');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Forester', '10004.7');
INSERT INTO car (make, model, price) values ('MAZDA', 'Aviator', '77758.86');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Cougar', '18135.62');
INSERT INTO car (make, model, price) values ('GMC', 'Passat', '78178.58');
INSERT INTO car (make, model, price) values ('Acura', 'Avalanche', '19181.36');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Beetle', '10002.94');
INSERT INTO car (make, model, price) values ('Acura', 'Bronco', '10773.96');
INSERT INTO car (make, model, price) values ('Chevrolet', 'E250 Cargo', '10062.16');
INSERT INTO car (make, model, price) values ('Volkswagen', 'M5', '10003.4');
INSERT INTO car (make, model, price) values ('Toyota', 'Grand Prix', '46804.05');
INSERT INTO car (make, model, price) values ('Nissan', 'Elantra GT', '10053.15');
INSERT INTO car (make, model, price) values ('Audi', 'Dakota Regular Cab', '10772.54');
INSERT INTO car (make, model, price) values ('Acura', 'Sierra 1500 Extended Cab', '10005.56');
INSERT INTO car (make, model, price) values ('GMC', 'R8', '10416.06');
INSERT INTO car (make, model, price) values ('Toyota', 'Optima', '49165.47');
INSERT INTO car (make, model, price) values ('Ford', 'MAZDA6', '10490.43');
INSERT INTO car (make, model, price) values ('Volkswagen', '2500 Extended Cab', '103435.47');
INSERT INTO car (make, model, price) values ('Ram', 'Santa Fe', '10036.65');
INSERT INTO car (make, model, price) values ('Chrysler', 'XTS', '10551.06');
INSERT INTO car (make, model, price) values ('Nissan', 'Cavalier', '40711.2');
INSERT INTO car (make, model, price) values ('Dodge', 'Sienna', '10334.67');
INSERT INTO car (make, model, price) values ('Mercury', 'Probe', '104576.43');
INSERT INTO car (make, model, price) values ('Nissan', 'Monte Carlo', '10001.19');
INSERT INTO car (make, model, price) values ('Lexus', 'Land Cruiser', '14502.41');
INSERT INTO car (make, model, price) values ('MINI', 'RAV4', '10091.87');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'X6 M', '10007.37');
INSERT INTO car (make, model, price) values ('Pontiac', 'LeSabre', '10001.62');
INSERT INTO car (make, model, price) values ('Mercury', 'Spectra', '10002.88');
INSERT INTO car (make, model, price) values ('Nissan', 'Imperial', '82143.81');
INSERT INTO car (make, model, price) values ('Toyota', 'Accent', '10750.32');
INSERT INTO car (make, model, price) values ('Jeep', '2500 Regular Cab', '28318.33');
INSERT INTO car (make, model, price) values ('Kia', 'Savana 2500 Passenger', '10492.65');
INSERT INTO car (make, model, price) values ('Nissan', '2500 Crew Cab', '46445.54');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Fiesta', '10078.2');
INSERT INTO car (make, model, price) values ('MAZDA', 'Edge', '10645.17');
INSERT INTO car (make, model, price) values ('Volvo', 'Murano', '10520.58');
INSERT INTO car (make, model, price) values ('Ford', 'Silverado 2500 HD Extended Cab', '10001.18');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Z3', '10003.1');
INSERT INTO car (make, model, price) values ('INFINITI', 'R8', '10026.66');
INSERT INTO car (make, model, price) values ('Ford', 'Avenger', '10055.16');
INSERT INTO car (make, model, price) values ('Ford', 'Veloster', '10019.7');
INSERT INTO car (make, model, price) values ('Dodge', 'Dynasty', '10084.36');
INSERT INTO car (make, model, price) values ('Dodge', 'JUKE', '75136.96');
INSERT INTO car (make, model, price) values ('BMW', 'Land Cruiser', '10020.15');
INSERT INTO car (make, model, price) values ('BMW', 'Neon', '10066.02');
INSERT INTO car (make, model, price) values ('Chevrolet', 'M5', '10612.38');
INSERT INTO car (make, model, price) values ('Saab', 'Vantage', '10001.6');
INSERT INTO car (make, model, price) values ('Nissan', 'S40', '10006.95');
INSERT INTO car (make, model, price) values ('Toyota', 'Escort', '10082.81');
INSERT INTO car (make, model, price) values ('BMW', 'Hardtop 4 Door', '13122.41');
INSERT INTO car (make, model, price) values ('Dodge', 'Caravan Cargo', '13254.68');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Q', '84180.57');
INSERT INTO car (make, model, price) values ('Dodge', 'D350 Club Cab', '13766.95');
INSERT INTO car (make, model, price) values ('Acura', 'MAZDA6', '62035.41');
INSERT INTO car (make, model, price) values ('Subaru', 'Torrent', '19203.83');
INSERT INTO car (make, model, price) values ('Cadillac', 'V70', '13499.46');
INSERT INTO car (make, model, price) values ('Land Rover', '2 Series', '64773.27');
INSERT INTO car (make, model, price) values ('Dodge', 'A6', '10107.73');
INSERT INTO car (make, model, price) values ('Mercury', 'Camry', '10000.2');
INSERT INTO car (make, model, price) values ('Buick', '911', '10000.51');
INSERT INTO car (make, model, price) values ('GMC', 'Ranger Regular Cab', '10005.56');
INSERT INTO car (make, model, price) values ('Toyota', 'Roadster', '95339.29');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Optima Hybrid', '55942.74');
INSERT INTO car (make, model, price) values ('Dodge', 'F150 Regular Cab', '10023.64');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Tundra Regular Cab', '49585.54');
INSERT INTO car (make, model, price) values ('Dodge', 'Roadmaster', '10008.49');
INSERT INTO car (make, model, price) values ('Ford', 'Model S', '16581.88');
INSERT INTO car (make, model, price) values ('Chevrolet', 'XJ', '10553.57');
INSERT INTO car (make, model, price) values ('Kia', 'Montana', '16863.89');
INSERT INTO car (make, model, price) values ('Ford', 'G6 (2009.5)', '10731.67');
INSERT INTO car (make, model, price) values ('Ford', 'MX-5 Miata RF', '11188.85');
INSERT INTO car (make, model, price) values ('Honda', 'S-Class', '10034.0');
INSERT INTO car (make, model, price) values ('Porsche', 'Jetta', '10005.19');
INSERT INTO car (make, model, price) values ('Audi', 'A6', '10059.87');
INSERT INTO car (make, model, price) values ('Chevrolet', 'F150 Super Cab', '15941.0');
INSERT INTO car (make, model, price) values ('Dodge', '3500 Crew Cab', '10061.35');
INSERT INTO car (make, model, price) values ('Buick', 'Ram 1500 Regular Cab', '10005.54');
INSERT INTO car (make, model, price) values ('Subaru', 'GLC', '10003.49');
INSERT INTO car (make, model, price) values ('Nissan', 'Suburban 3500HD', '99683.63');
INSERT INTO car (make, model, price) values ('Nissan', 'ES', '54204.33');
INSERT INTO car (make, model, price) values ('INFINITI', 'Ghost', '11717.85');
INSERT INTO car (make, model, price) values ('Volvo', '3000GT', '10051.76');
INSERT INTO car (make, model, price) values ('Audi', 'Econoline E250 Cargo', '10740.26');
INSERT INTO car (make, model, price) values ('GMC', 'Terraza', '10006.87');
INSERT INTO car (make, model, price) values ('Kia', 'Colt', '10001.99');
INSERT INTO car (make, model, price) values ('Rolls-Royce', 'A3', '10006.59');
INSERT INTO car (make, model, price) values ('Pontiac', 'Maxima', '19451.02');
INSERT INTO car (make, model, price) values ('Buick', 'Suburban', '16389.35');
INSERT INTO car (make, model, price) values ('Audi', 'Colorado Regular Cab', '10748.38');
INSERT INTO car (make, model, price) values ('Jeep', 'Astro Cargo', '10000.15');
INSERT INTO car (make, model, price) values ('Buick', '2500 Extended Cab', '10004.76');
INSERT INTO car (make, model, price) values ('Dodge', 'LR3', '10007.21');
INSERT INTO car (make, model, price) values ('Lincoln', 'F350 Super Duty Super Cab', '10040.29');
INSERT INTO car (make, model, price) values ('Subaru', 'Escort', '19420.55');
INSERT INTO car (make, model, price) values ('Dodge', 'Beetle', '10028.09');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Passat', '10338.07');
INSERT INTO car (make, model, price) values ('Ford', '626', '16888.1');
INSERT INTO car (make, model, price) values ('Acura', 'Transit 150 Wagon', '10025.23');
INSERT INTO car (make, model, price) values ('BMW', 'Avalanche 1500', '10831.43');
INSERT INTO car (make, model, price) values ('Dodge', 'Touareg', '10719.81');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Tundra Regular Cab', '23425.1');
INSERT INTO car (make, model, price) values ('Chrysler', 'Accord', '10924.63');
INSERT INTO car (make, model, price) values ('Nissan', 'Avenger', '10402.98');
INSERT INTO car (make, model, price) values ('Ram', 'Rogue Sport', '109595.81');
INSERT INTO car (make, model, price) values ('Kia', 'LHS', '10009.66');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', '500e', '10004.42');
INSERT INTO car (make, model, price) values ('Nissan', 'ILX', '81562.89');
INSERT INTO car (make, model, price) values ('Dodge', 'Montero', '10148.51');
INSERT INTO car (make, model, price) values ('Cadillac', 'Sephia', '43887.21');
INSERT INTO car (make, model, price) values ('Volvo', 'C-Class', '10009.81');
INSERT INTO car (make, model, price) values ('Nissan', 'Mountaineer', '31483.42');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'CLK-Class', '10351.51');
INSERT INTO car (make, model, price) values ('Ford', 'R8', '10008.26');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Pacifica Hybrid', '10008.19');
INSERT INTO car (make, model, price) values ('Nissan', 'XK', '10000.54');
INSERT INTO car (make, model, price) values ('Ram', 'Town & Country', '105262.92');
INSERT INTO car (make, model, price) values ('Lincoln', 'Mountaineer', '10075.73');
INSERT INTO car (make, model, price) values ('Ford', 'Ranger Regular Cab', '18722.01');
INSERT INTO car (make, model, price) values ('Ford', 'Cadenza', '10049.37');
INSERT INTO car (make, model, price) values ('Lamborghini', 'Yukon XL', '10005.18');
INSERT INTO car (make, model, price) values ('GMC', 'V70', '10005.38');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', '62', '10672.87');
INSERT INTO car (make, model, price) values ('BMW', 'XK', '10005.82');
INSERT INTO car (make, model, price) values ('BMW', 'Impala', '10929.57');
INSERT INTO car (make, model, price) values ('Ford', 'Optima', '10004.81');
INSERT INTO car (make, model, price) values ('Jaguar', 'Escape', '10331.32');
INSERT INTO car (make, model, price) values ('Dodge', 'Tribute', '10008.98');
INSERT INTO car (make, model, price) values ('Honda', 'M6', '94830.96');
INSERT INTO car (make, model, price) values ('Buick', 'Tundra Regular Cab', '74526.71');
INSERT INTO car (make, model, price) values ('Chevrolet', 'E150 Super Duty Passenger', '10004.13');
INSERT INTO car (make, model, price) values ('Volkswagen', 'MKZ', '17367.52');
INSERT INTO car (make, model, price) values ('BMW', 'Beetle', '10034.62');
INSERT INTO car (make, model, price) values ('HUMMER', 'S5', '10061.74');
INSERT INTO car (make, model, price) values ('BMW', 'Axiom', '10059.82');
INSERT INTO car (make, model, price) values ('Cadillac', 'Outlander PHEV', '10006.72');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Wrangler', '57610.48');
INSERT INTO car (make, model, price) values ('Buick', '2500 Regular Cab', '10063.79');
INSERT INTO car (make, model, price) values ('Ford', 'Ram 2500 Regular Cab', '18560.79');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Express 3500 Passenger', '10538.02');
INSERT INTO car (make, model, price) values ('BMW', 'Seville', '74504.3');
INSERT INTO car (make, model, price) values ('Bentley', 'Mercedes-AMG E-Class', '13390.65');
INSERT INTO car (make, model, price) values ('Ford', 'Prelude', '10000.09');
INSERT INTO car (make, model, price) values ('Jaguar', 'Bonneville', '10534.82');
INSERT INTO car (make, model, price) values ('Pontiac', 'LeBaron', '10041.69');
INSERT INTO car (make, model, price) values ('Nissan', 'Ram Wagon 3500', '10001.89');
INSERT INTO car (make, model, price) values ('Ferrari', 'Seville', '10000.36');
INSERT INTO car (make, model, price) values ('Ford', '7 Series', '10057.57');
INSERT INTO car (make, model, price) values ('Scion', 'S8', '79063.42');
INSERT INTO car (make, model, price) values ('Volkswagen', 'X1', '10006.2');
INSERT INTO car (make, model, price) values ('Chevrolet', 'S-Series', '10020.8');
INSERT INTO car (make, model, price) values ('Dodge', 'Intrigue', '10044.4');
INSERT INTO car (make, model, price) values ('Ford', 'Sierra (Classic) 1500 Regular Cab', '50964.79');
INSERT INTO car (make, model, price) values ('Acura', 'Silverado 1500 Regular Cab', '42243.02');
INSERT INTO car (make, model, price) values ('Ford', 'S5', '10074.67');
INSERT INTO car (make, model, price) values ('Chrysler', 'CLK-Class', '10001.77');
INSERT INTO car (make, model, price) values ('MAZDA', 'GLA', '18202.44');
INSERT INTO car (make, model, price) values ('Audi', 'GranTurismo', '10001.19');
INSERT INTO car (make, model, price) values ('Honda', 'RX', '30861.7');
INSERT INTO car (make, model, price) values ('BMW', 'Fit', '10009.11');
INSERT INTO car (make, model, price) values ('Plymouth', 'Sienna', '10001.75');
INSERT INTO car (make, model, price) values ('Hyundai', 'S80', '10079.96');
INSERT INTO car (make, model, price) values ('Chrysler', 'Transit Connect Passenger', '10001.07');
INSERT INTO car (make, model, price) values ('Hyundai', 'GL-Class', '10001.21');
INSERT INTO car (make, model, price) values ('Ferrari', 'Sentra', '10083.13');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Cadenza', '10026.34');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Santa Fe', '66745.99');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'E150 Super Duty Cargo', '10246.05');
INSERT INTO car (make, model, price) values ('Chevrolet', 'A6', '10762.47');
INSERT INTO car (make, model, price) values ('Ford', 'Range Rover', '14529.35');
INSERT INTO car (make, model, price) values ('Saturn', 'Silverado 1500 Crew Cab', '10037.57');
INSERT INTO car (make, model, price) values ('MAZDA', '4Runner', '10009.83');
INSERT INTO car (make, model, price) values ('Honda', 'RAV4', '10666.88');
INSERT INTO car (make, model, price) values ('Audi', 'XV Crosstrek', '82608.57');
INSERT INTO car (make, model, price) values ('Volkswagen', '6 Series', '19569.1');
INSERT INTO car (make, model, price) values ('Ford', 'Tacoma Regular Cab', '19514.04');
INSERT INTO car (make, model, price) values ('Porsche', 'Titan King Cab', '10805.53');
INSERT INTO car (make, model, price) values ('Hyundai', 'CR-Z', '10081.5');
INSERT INTO car (make, model, price) values ('Nissan', 'Escalade', '10328.74');
INSERT INTO car (make, model, price) values ('Volvo', 'Baja', '10007.37');
INSERT INTO car (make, model, price) values ('Toyota', 'Navigator', '10051.46');
INSERT INTO car (make, model, price) values ('MINI', 'TLX', '10008.46');
INSERT INTO car (make, model, price) values ('Chrysler', 'Frontier Crew Cab', '10134.7');
INSERT INTO car (make, model, price) values ('BMW', 'LS', '10006.11');
INSERT INTO car (make, model, price) values ('INFINITI', '7 Series', '10014.49');
INSERT INTO car (make, model, price) values ('BMW', 'Durango', '64081.15');
INSERT INTO car (make, model, price) values ('Audi', 'Lumina', '10044.68');
INSERT INTO car (make, model, price) values ('Dodge', 'Silverado 1500 Crew Cab', '90311.34');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', '3-Sep', '16632.43');
INSERT INTO car (make, model, price) values ('Ford', 'V70', '10022.6');
INSERT INTO car (make, model, price) values ('Plymouth', '488 Spider', '10007.85');
INSERT INTO car (make, model, price) values ('BMW', 'HHR', '10065.66');
INSERT INTO car (make, model, price) values ('Pontiac', 'Xterra', '10734.12');
INSERT INTO car (make, model, price) values ('Dodge', 'Equus', '13304.51');
INSERT INTO car (make, model, price) values ('GMC', 'MKZ', '10476.08');
INSERT INTO car (make, model, price) values ('Cadillac', 'Soul', '10418.21');
INSERT INTO car (make, model, price) values ('Land Rover', 'Silverado 3500 Crew Cab', '10014.15');
INSERT INTO car (make, model, price) values ('Subaru', 'Odyssey', '12332.07');
INSERT INTO car (make, model, price) values ('GMC', 'Sprinter WORKER Passenger', '10387.01');
INSERT INTO car (make, model, price) values ('Toyota', 'Edge', '11064.85');
INSERT INTO car (make, model, price) values ('Hyundai', '2500 Regular Cab', '15318.81');
INSERT INTO car (make, model, price) values ('Ford', 'DB9 GT', '10021.64');
INSERT INTO car (make, model, price) values ('INFINITI', 'Traverse', '10745.71');
INSERT INTO car (make, model, price) values ('Alfa Romeo', 'Savana 3500 Cargo', '53025.24');
INSERT INTO car (make, model, price) values ('Audi', 'NV3500 HD Cargo', '17189.31');
INSERT INTO car (make, model, price) values ('Ford', 'Equinox', '25893.6');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'CLA-Class', '18648.11');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Celica', '10076.62');
INSERT INTO car (make, model, price) values ('Honda', 'F-TYPE', '18650.4');
INSERT INTO car (make, model, price) values ('GMC', 'Savana 3500 Passenger', '10312.77');
INSERT INTO car (make, model, price) values ('Ferrari', '1500 Regular Cab', '10008.61');
INSERT INTO car (make, model, price) values ('Ford', 'D150 Regular Cab', '10004.68');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Silverado 1500 Regular Cab', '10056.75');
INSERT INTO car (make, model, price) values ('Lexus', '190 E', '10139.65');
INSERT INTO car (make, model, price) values ('Hyundai', 'Sierra 2500 HD Regular Cab', '76645.21');
INSERT INTO car (make, model, price) values ('Ford', 'Boxster', '10006.36');
INSERT INTO car (make, model, price) values ('Saab', 'Jimmy', '10060.72');
INSERT INTO car (make, model, price) values ('Subaru', 'Ranger Super Cab', '18576.15');
INSERT INTO car (make, model, price) values ('Pontiac', 'Silverado 3500 HD Crew Cab', '59762.88');
INSERT INTO car (make, model, price) values ('Jaguar', 'C-Class', '89807.27');
INSERT INTO car (make, model, price) values ('Subaru', 'Grand Am', '10477.83');
INSERT INTO car (make, model, price) values ('Nissan', 'Bravada', '10067.81');
INSERT INTO car (make, model, price) values ('Subaru', 'Golf', '10430.39');
INSERT INTO car (make, model, price) values ('Hyundai', 'Mirage G4', '10999.23');
INSERT INTO car (make, model, price) values ('Chevrolet', 'LR2', '80483.29');
INSERT INTO car (make, model, price) values ('Lotus', 'Camry', '10500.84');
INSERT INTO car (make, model, price) values ('Nissan', 'MX-5 Miata', '10043.32');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Bronco', '47154.51');
INSERT INTO car (make, model, price) values ('Chevrolet', 'NV1500 Cargo', '10001.26');
INSERT INTO car (make, model, price) values ('Nissan', 'Q40', '59655.55');
INSERT INTO car (make, model, price) values ('Cadillac', 'Frontier Crew Cab', '10097.49');
INSERT INTO car (make, model, price) values ('smart', 'Tacoma Xtracab', '10052.57');
INSERT INTO car (make, model, price) values ('Nissan', 'S4', '12394.91');
INSERT INTO car (make, model, price) values ('Toyota', 'Celica', '10000.22');
INSERT INTO car (make, model, price) values ('Lamborghini', '940', '12047.87');
INSERT INTO car (make, model, price) values ('BMW', 'Savana 3500 Cargo', '13009.44');
INSERT INTO car (make, model, price) values ('Lexus', 'Neon', '10006.57');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Grand Caravan Passenger', '49532.57');
INSERT INTO car (make, model, price) values ('Nissan', 'Avenger', '13536.4');
INSERT INTO car (make, model, price) values ('Kia', 'GT', '10508.11');
INSERT INTO car (make, model, price) values ('Chrysler', 'Safari Passenger', '10548.54');
INSERT INTO car (make, model, price) values ('Ram', 'XK', '10007.94');
INSERT INTO car (make, model, price) values ('Nissan', 'CL-Class', '10001.49');
INSERT INTO car (make, model, price) values ('GMC', 'XT5', '10077.17');
INSERT INTO car (make, model, price) values ('Nissan', 'E350 Super Duty Passenger', '10009.71');
INSERT INTO car (make, model, price) values ('Chrysler', '960', '18340.34');
INSERT INTO car (make, model, price) values ('Subaru', 'Corolla iM', '16500.36');
INSERT INTO car (make, model, price) values ('Oldsmobile', 'Ascender', '17277.8');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'M5', '26839.77');
INSERT INTO car (make, model, price) values ('BMW', 'Sienna', '10008.49');
INSERT INTO car (make, model, price) values ('Hyundai', 'Silverado 1500 Extended Cab', '15679.42');
INSERT INTO car (make, model, price) values ('Kia', 'G-Class', '10868.91');
INSERT INTO car (make, model, price) values ('Dodge', 'F150 Regular Cab', '10059.49');
INSERT INTO car (make, model, price) values ('Dodge', 'Golf', '10424.15');
INSERT INTO car (make, model, price) values ('Chevrolet', 'LEAF', '10565.63');
INSERT INTO car (make, model, price) values ('Porsche', 'Golf GTI', '10550.53');
INSERT INTO car (make, model, price) values ('MAZDA', 'Caravan Passenger', '10008.01');
INSERT INTO car (make, model, price) values ('Lexus', 'MAZDA2', '11297.12');
INSERT INTO car (make, model, price) values ('Land Rover', 'Sequoia', '22245.02');
INSERT INTO car (make, model, price) values ('MAZDA', 'Grand Prix', '10004.78');
INSERT INTO car (make, model, price) values ('Ram', 'CC', '94632.67');
INSERT INTO car (make, model, price) values ('BMW', 'Discovery', '13099.07');
INSERT INTO car (make, model, price) values ('Dodge', 'CT5', '11453.02');
INSERT INTO car (make, model, price) values ('Chevrolet', '500c Abarth', '10007.35');
INSERT INTO car (make, model, price) values ('Cadillac', 'RL', '10003.21');
INSERT INTO car (make, model, price) values ('Acura', 'Expedition', '10098.2');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Jimmy', '10085.03');
INSERT INTO car (make, model, price) values ('Ferrari', 'Millenia', '13656.83');
INSERT INTO car (make, model, price) values ('HUMMER', '1500 Quad Cab', '10038.79');
INSERT INTO car (make, model, price) values ('Subaru', 'F350 Regular Cab', '12246.54');
INSERT INTO car (make, model, price) values ('Nissan', 'Forenza', '10078.16');
INSERT INTO car (make, model, price) values ('Ford', 'Torrent', '10601.52');
INSERT INTO car (make, model, price) values ('Tesla', 'Equus', '10139.09');
INSERT INTO car (make, model, price) values ('Mitsubishi', 'Civic', '10008.86');
INSERT INTO car (make, model, price) values ('Toyota', 'Quattroporte', '10006.11');
INSERT INTO car (make, model, price) values ('Ford', 'Quattroporte', '45975.87');
INSERT INTO car (make, model, price) values ('Audi', 'Club Wagon', '10038.24');
INSERT INTO car (make, model, price) values ('Nissan', 'TrailBlazer', '10053.05');
INSERT INTO car (make, model, price) values ('Toyota', 'Express 3500 Cargo', '15540.73');
INSERT INTO car (make, model, price) values ('Mercury', 'A4', '10009.5');
INSERT INTO car (make, model, price) values ('BMW', 'Avalon', '10030.06');
INSERT INTO car (make, model, price) values ('Dodge', '2500 HD Regular Cab', '10043.86');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Cruze', '58267.74');
INSERT INTO car (make, model, price) values ('Ford', 'M', '10191.95');
INSERT INTO car (make, model, price) values ('Nissan', 'CR-Z', '10052.31');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Swift', '13816.85');
INSERT INTO car (make, model, price) values ('Ford', 'A8', '15550.81');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'Mirage', '19832.97');
INSERT INTO car (make, model, price) values ('Freightliner', 'New Beetle', '10061.55');
INSERT INTO car (make, model, price) values ('Aston Martin', 'Ioniq Electric', '17687.36');
INSERT INTO car (make, model, price) values ('Mercury', 'ES', '13887.47');
INSERT INTO car (make, model, price) values ('Toyota', '940', '17059.32');
INSERT INTO car (make, model, price) values ('Ford', 'Stratus', '10005.94');
INSERT INTO car (make, model, price) values ('MAZDA', 'Tundra Double Cab', '10179.22');
INSERT INTO car (make, model, price) values ('Dodge', 'Ram 1500 Club Cab', '10000.86');
INSERT INTO car (make, model, price) values ('Lincoln', 'S10 Regular Cab', '10086.54');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Impreza', '10395.63');
INSERT INTO car (make, model, price) values ('Honda', 'RAV4', '10000.18');
INSERT INTO car (make, model, price) values ('Chevrolet', 'Range Rover Sport', '10569.51');
INSERT INTO car (make, model, price) values ('Chrysler', 'Altima', '28852.68');
INSERT INTO car (make, model, price) values ('Mercedes-Benz', 'X6 M', '10007.18');
INSERT INTO car (make, model, price) values ('Volkswagen', 'S80', '37901.08');
INSERT INTO car (make, model, price) values ('Maserati', 'Navigator L', '10006.74');
INSERT INTO car (make, model, price) values ('Volvo', 'Riviera', '10333.13');
INSERT INTO car (make, model, price) values ('Volkswagen', 'Dakota Crew Cab', '18378.3');
INSERT INTO car (make, model, price) values ('Lamborghini', 'GLS', '10615.55');
